[package]
name = "struct-and-getters"
version = "0.1.0"
authors = ["Lawrence Lu <lawrence@phorena.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1.0"
